var token="",acces_token="",acces_token_v="",aoo_user_id=0,aoolist_love_album_id=0,brand="brand=mmm2011",aoolist_love_album_title="Aoo!Enno",promo_gid="0",promo_host="aoo.xfactorial.com",aoo_all_list={},aoo_album_list={},aoo_promo_list={},aoo_release_list={},aoo_history_list={},aoo_love_list={},aoo_top_list={},aoo_search_list={},aoo_search_history="",search_busy=!1,search_more=!1,volume_curent=100,status_rest=!0,status_t_rest=!0,history_list=System.Gadget.Settings.readString("history_list"),aoo_user_id=
    System.Gadget.Settings.readString("aoo_user_id"),aoo_user_first_name=System.Gadget.Settings.readString("acces_token"),aoo_user_last_name=System.Gadget.Settings.readString("aoo_user_last_name"),aoo_user_img=System.Gadget.Settings.readString("aoo_user_img"),broadcast=System.Gadget.Settings.readString("broadcast"),active_track={all:0,album:0,love:0,promo:0,release:0,top:0,history:0,search:0},active_tab="promo",active_list="promo",aoolist_length={all:0,love:0,album:0,promo:0,release:0,top:0,history:0,
    search:0,offset:0},aoolist_active_num=1,current_slide=0,big_slider_show=null,get_big_slider_info=null,id_info_script=null,slides=null,status_upl_timeout,aoo_upload_track=0,stt="",baby=" Baby",gsDestFolder="c:\\temp\\aoo\\",WMState=[],scrobble_t=!1,timer_t,timer,scrollBox,scrollBar,scrollTab=!1;
function aoo_list(b){switch(b){case "promo":return aoo_promo_list;case "top":return aoo_top_list;case "release":return aoo_release_list;case "all":return aoo_all_list;case "love":return aoo_love_list;case "album":return aoo_album_list;case "search":return aoo_search_list;case "history":return aoo_history_list}}
function login(){acces_token=System.Gadget.Settings.readString("token");if(""==acces_token||"undefined"==typeof acces_token){FrURL="http://api.vk.com/oauth/authorize?client_id=2463163&scope=audio,wall,status,offline&redirect_uri=http://api.vk.com/blank.html&display=popup&response_type=token";if(IE0=new ActiveXObject("InternetExplorer.Application"))if(IE0.Height=100,IE0.Width=100,IE0.Visible=!1,IE=new ActiveXObject("InternetExplorer.Application")){IE.Height=100;IE.Width=100;IE.AddressBar=!1;IE.MenuBar=
    !1;IE.ToolBar=!1;IE.StatusBar=!1;IE.Visible=!0;IE.Navigate(FrURL);for(var b="",a="";""==b||b==FrURL||!0==IE.Visible||""==a;){"LocationURL"in IE&&void 0==IE.LocationURL&&(HmURL="http://aooplayer.com/welcome.php",IE0.Navigate(HmURL));var b=IE.LocationURL,b=b.substring(b.indexOf("#")+1),c=$.parseQuery(b);void 0!==c.error&&(a=c.error,HmURL="http://aooplayer.com/welcome.php",IE0.Navigate(HmURL));if(void 0!==c.access_token&&null!==c.acces_token&&""!==c.acces_token){acces_token=c.access_token;aoo_user_id=
    c.user_id;acces_token_v="access_token="+acces_token;System.Gadget.Settings.writeString("token",acces_token);System.Gadget.Settings.writeString("aoo_user_id",aoo_user_id);get_playlist("users.get",acces_token_v+"&fields=first_name,last_name,nickname,photo_medium_rec&uids="+aoo_user_id,null);HmURL="http://aooplayer.com/welcome.php?id="+aoo_user_id;IE0.Navigate(HmURL);if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=IE0.readystate;);
    IE0.Quit();delete IE0}return!0}}}if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=IE0.readystate;);IE0.Quit();delete IE0}return!1}get_playlist("users.get",acces_token_v+"&fields=first_name,last_name,nickname,photo_medium_rec&uids="+aoo_user_id,null)}
function init(){var b={},b=document.getElementById("player");b.settings.volume=volume_curent;System.Gadget.settingsUI="settings.html";$("#background").get(0);$(".sections").hide();System.Gadget.onDock=dockStateChanged;System.Gadget.onUndock=dockStateChanged;dockStateChanged();status("Login and play");status("I`m Waiting for You...");main();System.Gadget.onSettingsClosed=function(){main();getinfo()};stopnow()}
function main(){timer_t=document.getElementById("timer");timer=window.setInterval(function(){timer_t.innerHTML=player.controls.currentPositionString},1E3);lastfm.sk=System.Gadget.Settings.readString("lastfm_sk");lastfm.token=System.Gadget.Settings.readString("lastfm_token");lastfm.name=System.Gadget.Settings.readString("lastfm_name");lastfm.subscribe=System.Gadget.Settings.readString("lastfm_subscribe");acces_token=System.Gadget.Settings.readString("token");aoo_user_id=System.Gadget.Settings.readString("aoo_user_id");
    aoo_user_first_name=System.Gadget.Settings.readString("acces_token");aoo_user_last_name=System.Gadget.Settings.readString("aoo_user_last_name");aoo_user_img=System.Gadget.Settings.readString("aoo_user_img");broadcast=System.Gadget.Settings.readString("broadcast");""!=aoo_user_first_name&&(baby=" "+aoo_user_first_name);WMState[0]="Yea,"+baby+", click Play";WMState[1]="Why Stopped? Click Play!";WMState[2]="Why Paused? Click Play!";WMState[3]=baby+", I'm Playing for you!";WMState[4]="Scan Forward";WMState[5]=
        "Scan Reverse";WMState[6]="Waiting,"+baby+", music is buffering...";WMState[7]="Waiting,"+baby+", waiting...";WMState[8]="Media Ended";WMState[9]="Waiting,"+baby+", I`m Connecting...";WMState[10]="Yea,"+baby+", Ready!";WMState[11]="Waiting,"+baby+", I`m Reconnecting";$(document).ready(function(){"true"==System.Gadget.Settings.readString("shuffle")?$("#shuffle").addClass("on"):(System.Gadget.Settings.writeString("shuffle","false"),$("#shuffle").removeClass("on"));""==lastfm.sk||"undefined"==typeof lastfm.sk||
        ""==lastfm.token||"undefined"==typeof lastfm.token?$("#lastfm").removeClass("on"):$("#lastfm").addClass("on");""!=acces_token?(data=brand+"&getgid=1",get_playlist("promo_gid",data,"https://api.vk.com/method/audio.get"),acces_token_v="access_token="+acces_token,get_playlist("get_top","&limit=100"),get_playlist("all",acces_token_v),get_playlist("history_get",acces_token_v),0<aoolist_love_album_id?get_playlist("love",acces_token_v+"&album_id="+aoolist_love_album_id):get_playlist("get_love_album","id="+
        aoo_user_id+"&album_id="+aoolist_love_album_id)):(get_playlist("promo",brand),logoutTxt='<p align="center"><br><img src="includes/load-indicator.gif"></p>',document.getElementById("alllist").innerHTML=logoutTxt,document.getElementById("searchlist").innerHTML=logoutTxt,document.getElementById("lovelist").innerHTML=logoutTxt,document.getElementById("toplist").innerHTML=logoutTxt,document.getElementById("historylist").innerHTML=logoutTxt)})}
function send_aoo(b,a){var c=new XMLHttpRequest;c.open("POST",b+"?"+Math.random(),!0);c.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.setRequestHeader("Content-Length",a.length);c.setRequestHeader("Connection","close");c.send(a);c.onreadystatechange=function(){4==c.readyState&&200==c.status&&(vo=c.responseText)}}
function getinfo(){id_info_script&&document.body.removeChild(id_info_script);id_info_script=document.createElement("script");id_info_script.type="text/javascript";id_info_script.src="http://aooplayer.com/freeload2.php?ap="+Math.round(1E5*Math.random());document.body.appendChild(id_info_script)}
function big_slider_next(){slides=$("#big_slider .slide");clearInterval(big_slider_show);current_slide+=1;current_slide>slides.length-1&&(current_slide=0);$("#big_slider").scrollTo(".slide:eq("+current_slide+")",1E3);big_slider_show=window.setInterval(big_slider_next,1E4)}function big_slider_prev(){slides=$("#big_slider .slide");clearInterval(big_slider_show);current_slide-=1;0>current_slide&&(current_slide=slides.length-1);$("#big_slider").scrollTo(".slide:eq("+current_slide+")",1E3)}
function plusTop(b){void 0!==b?(list=active_tab,ptrack=b):(list=active_list,ptrack=active_track[active_list]);var a={},a=aoo_list(list),b=a.response[ptrack].aid,c=a.response[ptrack].owner_id,d=a.response[ptrack].title,a="aid="+b+"&oid="+c+"&artist="+encodeURIComponent(a.response[ptrack].artist)+"&title="+encodeURIComponent(d);send_aoo("http://aoo.xfactorial.com/top.php",a);history_list_array=history_list.split(",",200);new_history_item=c+"_"+b;if(1==history_list_array.length&&(""==history_list_array[0]||
    void 0==history_list_array[0]))history_list_array[0]=new_history_item,unshiftedh=1;unshiftedh=history_list_array.unshift(new_history_item);200<history_list_array.length&&history_list_array.splice(201,history_list_array.length-200);history_list=history_list_array.join(",");System.Gadget.Settings.writeString("history_list",history_list);acces_token_v="access_token="+acces_token;get_playlist("history_set","key=aoo_history&value="+history_list+"&"+acces_token_v)}
function get_playlist(b,a,c){status("Waiting "+aoo_user_first_name+" , Waiting...");var d="GET";switch(b){case "audio.save":c="https://api.vk.com/method/audio.save";break;case "getUploadServer":var e=c,c="https://api.vk.com/method/audio.getUploadServer";break;case "users.get":c="https://api.vk.com/method/users.get";break;case "lastfmLove":c="http://ws.audioscrobbler.com/2.0/";d="POST";break;case "scrobbling":c="http://ws.audioscrobbler.com/2.0/";d="POST";break;case "lastfmNowPlaying":c="http://ws.audioscrobbler.com/2.0/";
    d="POST";break;case "status_set":c="https://api.vk.com/method/status.set";break;case "promo_gid":c="http://aoo.xfactorial.com/brandplaylist.php";break;case "promo":c=void 0==c||0==promo_gid?"http://aoo.xfactorial.com/brandplaylist.php":"https://api.vk.com/method/audio.get";document.getElementById(b+"list").innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "get_top":c="http://aoo.xfactorial.com/top.php";break;case "top":c="https://api.vk.com/method/audio.getById";
    document.getElementById(b+"list").innerHTML='<p align="center">Loading Aoo!Top... <br><img src="includes/load-indicator.gif"></p>';break;case "release":c="http://aoo.xfactorial.com/brandplaylist.php";document.getElementById(b).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "all":c="https://api.vk.com/method/audio.get";document.getElementById(b+"list").innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';
    break;case "all_check":c="https://api.vk.com/method/audio.getCount";break;case "get_love_album":c="http://aoo.xfactorial.com/love_playlist.php";break;case "love":c="https://api.vk.com/method/audio.get";document.getElementById(b+"list").innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "add_love_album":c="https://api.vk.com/method/audio.addAlbum";break;case "album":c="http://aoo.xfactorial.com/brandplaylist.php";document.getElementById(b+"list").innerHTML=
    '<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "search":c="https://api.vk.com/method/audio.search";document.getElementById(b+"list").innerHTML='<p align="center">Searching... <br><img src="includes/load-indicator.gif"></p>';break;case "add":c="https://api.vk.com/method/audio.add";break;case "like":c="https://api.vk.com/method/audio.moveToAlbum";break;case "del":c="https://api.vk.com/method/audio.delete";break;case "share":c="https://api.vk.com/method/wall.post";
    break;case "history_get":c="https://api.vk.com/method/storage.get";a="key=aoo_history&"+a;break;case "history":c="https://api.vk.com/method/audio.getById";break;case "history_set":c="https://api.vk.com/method/storage.set"}var f=new XMLHttpRequest;"POST"==d?f.open(d,c,!0):f.open("GET",c+"?"+a,!0);f.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");f.setRequestHeader("Content-Type","application/x-www-form-urlencoded");"undefined"!=typeof a&&null!=a&&f.setRequestHeader("Content-Length",
    a.length);f.send(a);f.onreadystatechange=function(){if(4==f.readyState&&200==f.status){status("Ready!");switch(b){case "audio.save":qi=new $.parseJSON(f.responseText);void 0!==qi.error?(alert("Error "+qi.error.message),checkUpdates("all")):(aoo_upload_track-=1,0>=aoo_upload_track&&checkUpdates("all"));break;case "getUploadServer":qi=new $.parseJSON(f.responseText);if(void 0!==qi.error)alert("Error "+qi.error.message),aoo_upload_track=0,checkUpdates("all");else{WinHTTPPostRequest(qi.response.upload_url,
    e);return}break;case "users.get":qi=new $.parseJSON(f.responseText);void 0!==qi.error?aoo_user_img=aoo_user_last_name=aoo_user_first_name=acces_token="":(aoo_user_first_name=qi.response[0].first_name,aoo_user_last_name=qi.response[0].last_name,aoo_user_img='<img id="user" src="'+qi.response[0].photo_medium_rec+'">');System.Gadget.Settings.writeString("token",acces_token);System.Gadget.Settings.writeString("aoo_user_id",aoo_user_id);System.Gadget.Settings.writeString("aoo_user_first_name",aoo_user_first_name);
    System.Gadget.Settings.writeString("aoo_user_last_name",aoo_user_last_name);System.Gadget.Settings.writeString("aoo_user_img",aoo_user_img);break;case "lastfmNowPlaying":a=new $.parseJSON(f.responseText);"undefined"!=typeof a.error&&alert("OOOPS!! Last.fm error #"+a.error+"."+a.message+".");break;case "status_set":new $.parseJSON(f.responseText);break;case "promo_gid":a=new $.parseJSON(f.responseText);promo_host=a.response[0].host;promo_gid=a.response[0].gid;get_playlist("promo",brand);data_v="access_token="+
    acces_token+"&gid="+promo_gid;get_playlist("promo",data_v,"https://api.vk.com/method/audio.get");break;case "promo":a=new $.parseJSON(f.responseText);if(!("host"in a.response[0])&&"error"in a)return promo_host="aoo.xfactorial.com",promo_gid=0,get_playlist("promo",brand),!1;aoo_promo_list=new $.parseJSON(f.responseText);document.getElementById("promolist").innerHTML=render_playlist(aoo_promo_list,b);break;case "get_top":get_playlist("top",acces_token_v+"&audios="+f.responseText);break;case "top":aoo_top_list=
    new $.parseJSON(f.responseText);if(void 0!==aoo_top_list.error)return document.getElementById(b+"list").innerHTML='<p align="center">Please open settings...<br><img src="includes/load-indicator.gif"></p>',!1;document.getElementById(b+"list").innerHTML=render_playlist(aoo_top_list,b);break;case "all_check":qi=new $.parseJSON(f.responseText);if(void 0!==qi.error)return!1;qi.response!=aoo_all_list.response.length&&""!=acces_token&&(get_playlist("all",acces_token_v),0<aoolist_love_album_id?get_playlist("love",
    acces_token_v+"&album_id="+aoolist_love_album_id):get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id));break;case "all":aoo_all_list=new $.parseJSON(f.responseText);if(void 0!==aoo_all_list.error)return document.getElementById(b+"list").innerHTML='<p align="center">Please open settings...<br><img src="includes/load-indicator.gif"></p>',!1;document.getElementById(b+"list").innerHTML=render_playlist(aoo_all_list,b);break;case "search":aoo_search_list=new Del_dubs($.parseJSON(f.responseText),
    "search");if("error"in aoo_search_list)return document.getElementById("searchlist").innerHTML='<p align="center"><br><img src="includes/load-indicator.gif"></p>',!1;document.getElementById("searchlist").innerHTML=render_playlist(aoo_search_list,b);break;case "get_love_album":return 0<f.responseText?(aoolist_love_album_id=f.responseText,data_v=acces_token_v+"&album_id="+aoolist_love_album_id,get_playlist("love",data_v)):0<aoolist_love_album_id?get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+
    aoolist_love_album_id):(aoolist_love_album_id=f.responseText,get_playlist("add_love_album",acces_token_v+"&title="+aoolist_love_album_title)),!1;case "add_love_album":var a=new $.parseJSON(f.responseText);if("error"in a)return!1;aoolist_love_album_id=a.response.album_id;get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id);return!1;case "love":aoo_love_list=new $.parseJSON(f.responseText);if("error"in aoo_love_list)return document.getElementById("lovelist").innerHTML=
    '<p align="center">Please open settings...<br><img src="includes/load-indicator.gif"></p>',!1;document.getElementById("lovelist").innerHTML=render_playlist(aoo_love_list,b);break;case "like":actsObj=new $.parseJSON(f.responseText);if("error"in actsObj)return status("Sorry, I can`t.."),!1;get_playlist("love",acces_token_v+"&album_id="+aoolist_love_album_id);status("Yea, Baby! Track liked...");break;case "add":actsObj=new $.parseJSON(f.responseText);if(void 0!==actsObj.error)return status("Sorry, I can`t.."),
    !1;get_playlist("all",acces_token_v);status("Yea, Baby! Track added...");break;case "del":actsObj=new $.parseJSON(f.responseText);if(void 0!==actsObj.error){if(""==acces_token)return status("Sorry, I can`t. Login in"),!1}else get_playlist(active_tab,acces_token_v),status("Yea, Baby! Track removed...");break;case "share":actsObj=new $.parseJSON(f.responseText);if(void 0!==actsObj.error)return status("Sorry, I can`t share"),!1;status("Yea, Baby! Track shared...");break;case "history_get":aoo_history_get=
    new $.parseJSON(f.responseText);void 0!==aoo_history_get.error?(status("Sorry, I can`t get Your history now..."),history_list="",System.Gadget.Settings.writeString("history_list",history_list),get_playlist("history_set","key=aoo_history&value="+history_list+"&"+acces_token_v)):(history_list=aoo_history_get.response,get_playlist("history",acces_token_v+"&audios="+aoo_history_get.response));break;case "history":aoo_history_list=new Del_dubs($.parseJSON(f.responseText),b);if(void 0!==aoo_history_list.error)return document.getElementById(b+
    "list").innerHTML='<p align="center">Please open settings...<br><img src="includes/load-indicator.gif"></p>',!1;document.getElementById(b+"list").innerHTML=render_playlist(aoo_history_list,b);break;case "history_set":aoo_history_set=new $.parseJSON(f.responseText),(""===aoo_history_set.response||"error"in aoo_history_set)&&status("Sorry, I can`t set Your history now...")}updatePositionTab()}}}
function searching(b){b=encodeURIComponent(b);if("undefined"==typeof b||null==b||""==b)b=encodeURIComponent($("#insearch").val());var a="offset="+aoolist_length.offset+"&";search_busy=!0;get_playlist("search","q="+b+"&auto_complete=1&sort=0&lyrics=0&count=200&"+a+"&"+acces_token_v)}
function Del_dubs(b,a){if(!("error"in b)){"search"==a&&(aoolist_length.search=b.response[0],b.response.splice(0,1));for(var c=b.response.length,d=0,d=0;d<c;d++){for(var e=b.response[d].artist.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," "),f=b.response[d].title.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," "),h=d+1,h=d+1;h<c;h++){var l=b.response[h].artist.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig,
    " ").replace(/\s+/g," "),m=b.response[h].title.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," ");e==l&&f==m&&(b.response.splice(h,1),c--)}"search"==a&&!0==search_more&&aoo_search_list.response.push(b.response[d])}}if("search"==a&&!0==search_more)return aoolist_length[a]=aoo_search_list.response.length,aoo_search_list;aoolist_length[a]=c;return b}
function render_playlist(b,a){for(var c=b.response.length,d="<ul>",e=0,e=0;e<c;e++){var f=e+1,h='<div class="acts">';switch(a){case "promo":h+='<a class="acts_add" title="Add"></a><a class="acts_share" title="Share"></a>';break;case "all":h+='<a class="acts_del" title="Delete"></a><a class="acts_like" title="Aoo!Enno"></a><a class="acts_share" title="Share"></a>';break;case "love":h+='<a class="acts_del" title="Delete"></a><a class="acts_unlike" title="UnLike"></a><a class="acts_share" title="Share"></a>';
    break;case "album":h+='<a class="acts_del" title="Delete"></a><a class="acts_share" title="Share"></a>';break;case "search":h+='<a class="acts_add" title="Add"></a><a class="acts_share" title="Share"></a>';break;case "top":h+='<a class="acts_add" title="Add"></a><a class="acts_share" title="Share"></a>';break;case "history":h+='<a class="acts_add" title="Add"></a><a class="acts_share" title="Share"></a>'}h+="</div>";d=d+'<li class="toplay" id="'+a+e+'"><div class="aootrack"><span class="artist">'+
    b.response[e].artist+" </span><b>"+f+'</b>. <span class="title">'+b.response[e].title+"</span></div>"+h+"</li>"}"search"==a&&aoolist_length.offset<aoolist_length.search&&(d+='<li><a id="extrasearch">More...<br><br><br></a></li>');aoolist_length[a]=c;search_busy=!1;return d+"</ul>"}
function play(){$("#play").fadeIn();$("#pause").hide();var b={},b=aoo_list(active_list);switch(player.playState){case 0:0>active_track[active_list]&&(active_track[active_list]=0);status_t();player.URL=b.response[active_track[active_list]].url;player.controls.play();volume(volume_curent);status(player.playState);sel_active_track(active_tab);break;case 1:status_t();player.URL=b.response[active_track[active_list]].url;player.controls.play();volume(volume_curent);status(player.playState);sel_active_track(active_tab);
    break;case 2:status_t();player.controls.play();volume(volume_curent);status(player.playState);sel_active_track(active_list);break;case 3:volume(volume_curent);status(player.playState);break;case 8:volume(0),stopnow(),scrobble_t=!0,window.setTimeout(next,500)}}function scrobble(b,a,c){if(player.controls.currentPosition>=c/2||0==player.controls.currentPosition&&scrobble_t)scrobble_t=!1,""!=lastfm.sk&&"undefined"!=typeof lastfm.sk&&get_playlist("scrobbling",lastfm.toScrobble(b,a,c),null),plusTop()}
function next(){volume(0);var b={},b=aoo_list(active_list);scrobble(b.response[active_track[active_list]].artist,b.response[active_track[active_list]].title,b.response[active_track[active_list]].duration);if("true"==System.Gadget.Settings.readString("shuffle")){var a=active_track[active_list];active_track[active_list]=Math.floor(Math.random()*aoolist_length[active_list]);a==active_track[active_list]&&(active_track[active_list]+=1)}else active_track[active_list]+=1;active_track[active_list]>aoolist_length[active_list]-
    1&&(active_track[active_list]=0);status_t();player.URL=b.response[active_track[active_list]].url;player.controls.play();volume(volume_curent);$("#play").fadeIn();$("#pause").hide();status(player.playState);sel_active_track(active_tab);return!0}
function prev(){volume(0);var b={},b=aoo_list(active_list);scrobble(b.response[active_track[active_list]].artist,b.response[active_track[active_list]].title,b.response[active_track[active_list]].duration);if("true"==System.Gadget.Settings.readString("shuffle")){var a=active_track[active_list];active_track[active_list]=Math.floor(Math.random()*aoolist_length[active_list]);a==active_track[active_list]&&(active_track[active_list]-=1)}else active_track[active_list]-=1;0>active_track[active_list]&&(active_track[active_list]=
    aoolist_length[active_list]-1);status_t();player.URL=b.response[active_track[active_list]].url;player.controls.play();volume(volume_curent);$("#play").fadeIn();$("#pause").hide();status(player.playState);sel_active_track(active_tab);return!0}function pause(){volume(0);$("#play").hide();$("#pause").fadeIn();player.controls.pause();status(player.playState);return!1}function stopnow(){volume(0);player.controls.stop();status(player.playState)}function volume(b){player.settings.volume=b}
function dockStateChanged(){if(System.Gadget.docked){var b="158px",a="66px";$(".sections").hide();$("#background").css("width",b).css("height",a).attr("src","./includes/aoo_background.png");$(document.body).removeClass("docked").addClass("undocked").css("width",b).css("height",a)}else b="158px",a="280px",$("#background").css("width",b).css("height",a).attr("src","./includes/aoo_background_big.png"),$(document.body).removeClass("undocked").addClass("docked").css("width",b).css("height",a),$(".sections").fadeIn(),
    $(function(){var a=$(".sections > div.box");a.hide().filter(active_list).show();"release"!=active_tab?($("#scrollBar").fadeOut(),updatePositionTab()):$("#scrollBar").fadeIn();$("div.sections ul.tabs a").click(function(){var b=$(this);active_tab_hash=this.hash;void 0!=typeof acces_token&&""!=acces_token?(a.hide(),active_tab=active_tab_hash.substring(1),a.filter(active_tab_hash).show(),$("div.sections ul.tabs a").removeClass("current"),b.addClass("current"),"release"==active_tab?($("#scrollBar").fadeOut(),
        getinfo()):($("#scrollBar").fadeIn(),active_tab==active_list?sel_active_track(active_tab):updatePositionTab())):"promo"==active_tab_hash.substring(1)||"release"==active_tab_hash.substring(1)?(a.hide(),active_tab=active_tab_hash.substring(1),a.filter(active_tab_hash).show(),$("div.sections ul.tabs a").removeClass("current"),b.addClass("current"),"release"==active_tab?($("#scrollBar").fadeOut(),getinfo()):($("#scrollBar").fadeIn(),active_tab==active_list?sel_active_track(active_tab):updatePositionTab())):
        (active_list="promo",status("Please open settings... "));return!1});$("div.sections ul.tabs a").filter(":first").click();$("div.sections ul.tabs a").dblclick(function(){if(void 0!=typeof acces_token&&""!=acces_token){var b=$(this);a.hide();active_tab_hash=this.hash;active_tab=active_tab_hash.substring(1);checkUpdates(active_tab);a.filter(active_tab_hash).show();$("div.sections ul.tabs a").removeClass("current");b.addClass("current");"release"==active_tab?$("#scrollBar").fadeOut():$("#scrollBar").fadeIn();
        return!1}status("Please open settings... ")})})}
function checkUpdates(b){acces_token_v="access_token="+acces_token;switch(b){case "promo":""!=acces_token?get_playlist("promo_gid",brand+"&getgid=1","https://api.vk.com/method/audio.get"):get_playlist("promo",brand);break;case "all":get_playlist("all_check",acces_token_v+"&oid="+aoo_user_id);break;case "love":""!=aoolist_love_album_id&&0<aoolist_love_album_id?get_playlist("love",acces_token_v+"&album_id="+aoolist_love_album_id):get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id);
    break;case "release":getinfo();break;case "top":get_playlist("get_top","&limit=100");break;case "history":get_playlist("history_get",acces_token_v)}}
function sel_active_track(b){if(void 0!=b){active_list=b;if(NaN==active_track[b]||void 0==active_track[b])active_track[b]=0;$("#"+b+"list ul li").eq(active_track[b]).is(".plaing")||($("#"+b+"list ul li.plaing").removeClass("plaing"),$("#"+b+"list ul li").eq(active_track[b]).addClass("plaing"),$("#"+b+"").scrollTo($(".plaing"),1E3,{margin:!1,offset:-5,easing:"easeInOutBack",onAfter:function(){active_list==active_tab&&updatePositionTab()}}))}}
function status(b){0>aoo_upload_track&&(aoo_upload_track=0);0!=aoo_upload_track?$("#uploading").fadeIn():$("#uploading").fadeOut();if("number"==typeof b||1==b.length)document.getElementById("status").innerHTML=WMState[b];else if("string"==typeof b){var a=function(){0==aoo_upload_track&&$("#uploading").fadeOut();clearTimeout(c);$("#status").fadeOut(function(){$(this).html(WMState[player.playState])}).fadeIn(function(){status_rest=!0});return!1};document.getElementById("status").innerHTML=b;b=="Waiting "+
    aoo_user_first_name+" , Waiting..."&&$("#uploading").fadeIn();clearTimeout(c);if(status_rest){status_rest=!1;var c=window.setTimeout(a,3E3)}}}
function status_t(b){function a(){var a={},b=0,e=0,f=0;aoolist_active_num=active_track[active_list]+1;a=aoo_list(active_list);"duration"in a.response[active_track[active_list]]&&"number"===typeof a.response[active_track[active_list]].duration&&(f=a.response[active_track[active_list]].duration,b=Math.floor(f/60),e=f-60*b,10>e&&(e="0"+e));var h=a.response[active_track[active_list]].artist,l=a.response[active_track[active_list]].title,m=a.response[active_track[active_list]].aid,i=a.response[active_track[active_list]].owner_id,
    a=aoolist_active_num+" . <a target='_blank' href='"+a.response[active_track[active_list]].url+"'>"+h+" - "+l+" | "+b+":"+e+"</a>";stt=document.getElementById("track").innerHTML=a;"true"==broadcast&&get_playlist("status_set","audio="+i+"_"+m+"&"+acces_token_v,null);""!=lastfm.sk&&"undefined"!=typeof lastfm.sk&&get_playlist("lastfmNowPlaying",lastfm.updateNowPlaying(h,l,f),null);return!0}void 0==b||NaN==b?a():$("#track").html(b,function(){$("#track").fadeIn(2E3);""!=stt&&a()})}
function actsAdd(b){var a={},a=aoo_list(active_tab);get_playlist("add","api_id=2463163&"+("aid="+a.response[b].aid+"&")+("oid="+a.response[b].owner_id+"&")+acces_token_v);plusTop(b)}
function actsLike(b,a){var c={},c=aoo_list(active_tab);get_playlist("like",acces_token_v+"&api_id=2463163&"+("&aids="+c.response[b].aid)+("&album_id="+a));plusTop(b);if(""!=lastfm.sk||"undefined"!=typeof lastfm.sk){var d=c.response[b].artist,c=c.response[b].title;0==a?get_playlist("lastfmLove",lastfm.lastfmUnLove(d,c),null):get_playlist("lastfmLove",lastfm.lastfmLove(d,c),null)}}
function actsDel(b){var a={},a=aoo_list(active_tab);get_playlist("del","aid="+a.response[b].aid+"&"+("oid="+a.response[b].owner_id+"&")+acces_token_v)}
function actsShare(b){var a={},a=aoo_list(active_tab),c=a.response[b].artist,d=a.response[b].title,e="message="+c+" - "+d+" #aooramusic #music &",a="attachments=audio"+a.response[b].owner_id+"_"+a.response[b].aid+"&";get_playlist("share",encodeURI("api_id=2463163&"+("message=#aooramusic "+c+" - "+d+"&")+a+"services=twitter, facebook&")+acces_token_v);get_playlist("share",encodeURI("api_id=2463163&owner_id=-42817636&from_group=1&signed=1&"+e+a+"services=twitter, facebook&")+acces_token_v);plusTop(b)}
function ProcessOneFile(b){var a=new ActiveXObject("Scripting.FileSystemObject"),c=new Date;c.getFullYear();("0"+(c.getMonth()+1)).slice(-2);("0"+c.getDate()).slice(-2);var c=a.GetFileName(b),d=gsDestFolder;a.CopyFile(b,d+c)}
function ProcessItemsFromDrop(){if(""==acces_token||"undefined"==typeof acces_token)return!1;for(var b=0,a;a=System.Shell.itemFromFileDrop(event.dataTransfer,b);)if(209715200>=a.size&&".mp3"==a.name.substr(a.name.length-4,4))get_playlist("getUploadServer",acces_token_v,a.path),aoo_upload_track++,b++;else return;status(""+aoo_upload_track+" file(s) uploading...")}
function cach_response(b){b=new $.parseJSON(b);get_playlist("audio.save",acces_token_v+"&server="+b.server+"&audio="+encodeURIComponent(b.audio)+"&hash="+b.hash)}function onScrollBoxDown(){scrollTab=!0}function onScrollBoxUp(){scrollTab=!1;updatePositionTab()}function onMouseMove(){scrollTab&&setTabPercent(scrollPositionTab(window.event.clientY))}function onMouseUp(){scrollTab&&(scrollTab=!1,setTabPercent(scrollPositionTab(window.event.clientY)),updatePositionTab())}
function scrollPositionTab(b){var a=document.getElementById("scrollBox"),c=document.getElementById("scrollBar"),a=c.offsetParent.offsetTop+c.offsetHeight-a.offsetHeight,d=c.offsetParent.offsetTop;b>a&&(b=a);b<d&&(b=d);return g=(b-c.offsetParent.offsetTop)/c.offsetHeight}
function setTabPercent(b){var a=document.getElementById("scrollBox"),c=document.getElementById("scrollBar"),d=$("#"+active_tab+"list ul"),e=document.getElementById(active_tab+"list"),f=Math.round(b*d.height());Math.abs(f)>d.height()-e.offsetHeight&&(f=d.height()-c.offsetHeight);a.style.top=Math.round(b*a.offsetParent.offsetHeight)+"px";$("#"+active_tab+"").animate({scrollTop:f},10)}
function updatePositionTab(){if(!scrollTab&&!scrollTab&&"release"!=active_tab){var b=document.getElementById("scrollBox"),a=document.getElementById("scrollBar"),c=document.getElementById(active_tab+"list");$("#"+active_tab+"list ul");var d=0,e=void 0;try{e=$("#"+active_tab+"list ul li").offset().top}catch(f){}finally{"undefined"!=typeof e&&(d=$("#"+active_tab+"list ul li").offset().top/c.scrollHeight)}b.style.top=Math.round(-d*a.offsetHeight)+"px";b.style.height=Math.round(a.offsetHeight*c.offsetHeight/
    c.scrollHeight)+"px"}}
$(document).ready(function(){document.getElementById("shuffle").onclick=function(){"true"==System.Gadget.Settings.readString("shuffle")?(System.Gadget.Settings.writeString("shuffle","false"),$(this).removeClass("on")):(System.Gadget.Settings.writeString("shuffle","true"),$(this).addClass("on"))};$(".to_search").live("click",function(){var b=$(this).attr("alt");if(""==b)return $(this).parent().find("a.site").fadeOut().fadeIn().fadeOut().fadeIn(),!1;void 0!=typeof acces_token&&""!=acces_token?($("#insearch").val(b),
    $(".searchicon").click(),searching(b)):status("Please open settings... Login")});$(".acts_add").live("click",function(){var b=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsAdd(b);$(this).parents(".toplay").stop().animate({opacity:"0.3"},"slow")});$(".acts_like").live("click",function(){var b=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsLike(b,aoolist_love_album_id)});$(".acts_unlike").live("click",function(){var b=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));
    actsLike(b,0);$(this).parents(".toplay").stop().animate({opacity:"0.3"},"slow")});$(".acts_del").live("click",function(){var b=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsDel(b);$(this).parents(".toplay").stop().animate({opacity:"0.3"},"slow")});$(".acts_share").live("click",function(){var b=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsShare(b)});$(".toplay").live("dblclick",function(){var b={},b=aoo_list(active_list);scrobble(b.response[active_track[active_list]].artist,
    b.response[active_track[active_list]].title,b.response[active_track[active_list]].duration);active_track[active_tab]=$("#"+active_tab+" ul li").index(this);volume(0);stopnow();b=aoo_list(active_list);status_t();player.URL=b.response[active_track[active_list]].url;player.controls.play();volume(volume_curent);$("#play").fadeIn();$("#pause").hide();status(player.playState);sel_active_track(active_tab);return!0});$("#extrasearch").live("click",function(){$("#extrasearch").parent("li").remove();search_more=
    !0;aoolist_length.offset+=199;searching()});$("#insearch").keydown(function(b){search_more=!1;if(!1==search_busy){if(8>b.which&&0<=b.which||8<b.which&&32>b.which)return!1;aoolist_length.offset=0;var a="",b=32>b.which?"":String.fromCharCode(b.which),a=$("#insearch").val()+b;searching(a)}});$(".box").mousewheel(function(b,a){$("#"+active_tab+"list ul").height();try{$("#"+active_tab+"list ul li").offset(),0<a?$(this).scrollTo("-="+20*Math.abs(a)+"px",100):0>a&&$(this).scrollTo("+="+20*Math.abs(a)+"px",
    100),updatePositionTab()}catch(c){}});$("#allcontrols").mousewheel(function(b,a){0<a&&100>=volume_curent+5?(volume_curent+=5,volume(volume_curent)):0>a&&0<=volume_curent-5&&(volume_curent-=5,volume(volume_curent));status("Volume "+volume_curent+"%")});$("a").focus(function(){$(this).blur()})});
jQuery.parseQuery=function(b,a){var c="string"===typeof b?b:window.location.search,d={f:function(a){return unescape(a).replace(/\+/g," ")}},d=jQuery.extend({},d,"object"===typeof b&&void 0===typeof a?b:a),e={};jQuery.each(c.match(/^\??(.*)$/)[1].split("&"),function(a,b){b=b.split("=");b[1]=d.f(b[1]);e[b[0]]=e[b[0]]?e[b[0]]instanceof Array?(e[b[0]].push(b[1]),e[b[0]]):[e[b[0]],b[1]]:b[1]});return e};
function clone(b){if(!b||"object"!==typeof b)return b;varc="function"===typeof b.pop?[]:{};var a,c,d=[];for(a in b)b.hasOwnProperty(a)&&(c=b[a],d[a]=c&&"object"===typeof c?clone(c):c);return d}function Stringify(b){var a="{",c=0,d;for(d in b)0<c&&(a+=", "),temp=b[d],s="object"==typeof temp?Stringify(temp):'"'+temp+'"',a+='"'+d+'":'+s,c++;return a+"}"}jQuery.easing.jswing=jQuery.easing.swing;
jQuery.extend(jQuery.easing,{def:"linear",swing:function(b,a,c,d,e){return jQuery.easing[jQuery.easing.def](b,a,c,d,e)},easeInQuad:function(b,a,c,d,e){return d*(a/=e)*a+c},easeOutQuad:function(b,a,c,d,e){return-d*(a/=e)*(a-2)+c},easeInOutQuad:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a+c:-d/2*(--a*(a-2)-1)+c},easeInCubic:function(b,a,c,d,e){return d*(a/=e)*a*a+c},easeOutCubic:function(b,a,c,d,e){return d*((a=a/e-1)*a*a+1)+c},easeInOutCubic:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a+c:d/2*((a-=
    2)*a*a+2)+c},easeInQuart:function(b,a,c,d,e){return d*(a/=e)*a*a*a+c},easeOutQuart:function(b,a,c,d,e){return-d*((a=a/e-1)*a*a*a-1)+c},easeInOutQuart:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a*a+c:-d/2*((a-=2)*a*a*a-2)+c},easeInQuint:function(b,a,c,d,e){return d*(a/=e)*a*a*a*a+c},easeOutQuint:function(b,a,c,d,e){return d*((a=a/e-1)*a*a*a*a+1)+c},easeInOutQuint:function(b,a,c,d,e){return 1>(a/=e/2)?d/2*a*a*a*a*a+c:d/2*((a-=2)*a*a*a*a+2)+c},easeInSine:function(b,a,c,d,e){return-d*Math.cos(a/e*
    (Math.PI/2))+d+c},easeOutSine:function(b,a,c,d,e){return d*Math.sin(a/e*(Math.PI/2))+c},easeInOutSine:function(b,a,c,d,e){return-d/2*(Math.cos(Math.PI*a/e)-1)+c},easeInExpo:function(b,a,c,d,e){return 0==a?c:d*Math.pow(2,10*(a/e-1))+c},easeOutExpo:function(b,a,c,d,e){return a==e?c+d:d*(-Math.pow(2,-10*a/e)+1)+c},easeInOutExpo:function(b,a,c,d,e){return 0==a?c:a==e?c+d:1>(a/=e/2)?d/2*Math.pow(2,10*(a-1))+c:d/2*(-Math.pow(2,-10*--a)+2)+c},easeInCirc:function(b,a,c,d,e){return-d*(Math.sqrt(1-(a/=e)*a)-
    1)+c},easeOutCirc:function(b,a,c,d,e){return d*Math.sqrt(1-(a=a/e-1)*a)+c},easeInOutCirc:function(b,a,c,d,e){return 1>(a/=e/2)?-d/2*(Math.sqrt(1-a*a)-1)+c:d/2*(Math.sqrt(1-(a-=2)*a)+1)+c},easeInElastic:function(b,a,c,d,e){var b=1.70158,f=0,h=d;if(0==a)return c;if(1==(a/=e))return c+d;f||(f=0.3*e);h<Math.abs(d)?(h=d,b=f/4):b=f/(2*Math.PI)*Math.asin(d/h);return-(h*Math.pow(2,10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/f))+c},easeOutElastic:function(b,a,c,d,e){var b=1.70158,f=0,h=d;if(0==a)return c;if(1==
    (a/=e))return c+d;f||(f=0.3*e);h<Math.abs(d)?(h=d,b=f/4):b=f/(2*Math.PI)*Math.asin(d/h);return h*Math.pow(2,-10*a)*Math.sin((a*e-b)*2*Math.PI/f)+d+c},easeInOutElastic:function(b,a,c,d,e){var b=1.70158,f=0,h=d;if(0==a)return c;if(2==(a/=e/2))return c+d;f||(f=e*0.3*1.5);h<Math.abs(d)?(h=d,b=f/4):b=f/(2*Math.PI)*Math.asin(d/h);return 1>a?-0.5*h*Math.pow(2,10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/f)+c:0.5*h*Math.pow(2,-10*(a-=1))*Math.sin((a*e-b)*2*Math.PI/f)+d+c},easeInBack:function(b,a,c,d,e,f){void 0==
    f&&(f=1.70158);return d*(a/=e)*a*((f+1)*a-f)+c},easeOutBack:function(b,a,c,d,e,f){void 0==f&&(f=1.70158);return d*((a=a/e-1)*a*((f+1)*a+f)+1)+c},easeInOutBack:function(b,a,c,d,e,f){void 0==f&&(f=1.70158);return 1>(a/=e/2)?d/2*a*a*(((f*=1.525)+1)*a-f)+c:d/2*((a-=2)*a*(((f*=1.525)+1)*a+f)+2)+c},easeInBounce:function(b,a,c,d,e){return d-jQuery.easing.easeOutBounce(b,e-a,0,d,e)+c},easeOutBounce:function(b,a,c,d,e){return(a/=e)<1/2.75?d*7.5625*a*a+c:a<2/2.75?d*(7.5625*(a-=1.5/2.75)*a+0.75)+c:a<2.5/2.75?
    d*(7.5625*(a-=2.25/2.75)*a+0.9375)+c:d*(7.5625*(a-=2.625/2.75)*a+0.984375)+c},easeInOutBounce:function(b,a,c,d,e){return a<e/2?0.5*jQuery.easing.easeInBounce(b,2*a,0,d,e)+c:0.5*jQuery.easing.easeOutBounce(b,2*a-e,0,d,e)+0.5*d+c}});
(function(b){function a(a){return"object"==typeof a?a:{top:a,left:a}}var c=b.scrollTo=function(a,c,f){b(window).scrollTo(a,c,f)};c.defaults={axis:"xy",duration:1.3<=parseFloat(b.fn.jquery)?0:1,limit:!0};c.window=function(){return b(window)._scrollable()};b.fn._scrollable=function(){return this.map(function(){if(this.nodeName&&-1==b.inArray(this.nodeName.toLowerCase(),["iframe","#document","html","body"]))return this;var a=(this.contentWindow||this).document||this.ownerDocument||this;return/webkit/i.test(navigator.userAgent)||
    "BackCompat"==a.compatMode?a.body:a.documentElement})};b.fn.scrollTo=function(d,e,f){"object"==typeof e&&(f=e,e=0);"function"==typeof f&&(f={onAfter:f});"max"==d&&(d=9E9);f=b.extend({},c.defaults,f);e=e||f.duration;f.queue=f.queue&&1<f.axis.length;f.queue&&(e/=2);f.offset=a(f.offset);f.over=a(f.over);return this._scrollable().each(function(){function h(a){m.animate(j,e,f.easing,a&&function(){a.call(this,d,f)})}if(null!=d){var l=this,m=b(l),i=d,n,j={},r=m.is("html,body");switch(typeof i){case "number":case "string":if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(i)){i=
    a(i);break}i=b(i,this);if(!i.length)return;case "object":if(i.is||i.style)n=(i=b(i)).offset()}b.each(f.axis.split(""),function(a,b){var d="x"==b?"Left":"Top",e=d.toLowerCase(),k="scroll"+d,p=l[k],q=c.max(l,b);n?(j[k]=n[e]+(r?0:p-m.offset()[e]),f.margin&&(j[k]-=parseInt(i.css("margin"+d))||0,j[k]-=parseInt(i.css("border"+d+"Width"))||0),j[k]+=f.offset[e]||0,f.over[e]&&(j[k]+=i["x"==b?"width":"height"]()*f.over[e])):(d=i[e],j[k]=d.slice&&"%"==d.slice(-1)?parseFloat(d)/100*q:d);f.limit&&/^\d+$/.test(j[k])&&
(j[k]=0>=j[k]?0:Math.min(j[k],q));!a&&f.queue&&(p!=j[k]&&h(f.onAfterFirst),delete j[k])});h(f.onAfter)}}).end()};c.max=function(a,c){var f="x"==c?"Width":"Height",h="scroll"+f;if(!b(a).is("html,body"))return a[h]-b(a)[f.toLowerCase()]();var f="client"+f,l=a.ownerDocument.documentElement,m=a.ownerDocument.body;return Math.max(l[h],m[h])-Math.min(l[f],m[f])}})(jQuery);
(function(b){b.event.special.mousewheel={setup:function(){var a=b.event.special.mousewheel.handler;b.browser.mozilla&&b(this).bind("mousemove.mousewheel",function(a){b.data(this,"mwcursorposdata",{pageX:a.pageX,pageY:a.pageY,clientX:a.clientX,clientY:a.clientY})});this.addEventListener?this.addEventListener(b.browser.mozilla?"DOMMouseScroll":"mousewheel",a,!1):this.onmousewheel=a},teardown:function(){var a=b.event.special.mousewheel.handler;b(this).unbind("mousemove.mousewheel");this.removeEventListener?
    this.removeEventListener(b.browser.mozilla?"DOMMouseScroll":"mousewheel",a,!1):this.onmousewheel=function(){};b.removeData(this,"mwcursorposdata")},handler:function(a){var c=Array.prototype.slice.call(arguments,1),a=b.event.fix(a||window.event);b.extend(a,b.data(this,"mwcursorposdata")||{});var d=0;a.wheelDelta&&(d=a.wheelDelta/120);a.detail&&(d=-a.detail/3);a.data=a.data||{};a.type="mousewheel";c.unshift(d);c.unshift(a);return b.event.handle.apply(this,c)}};b.fn.extend({mousewheel:function(a){return a?
    this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);