/* Иди нахуй злостный урод, взламывающий чужой код!
 Добро пожаловать в обитель радости и сверхлогичных решений добрый молодец, решивший усовершенствовать данный продукт*/
var token="",acces_token="",acces_token_v="",aoo_user_id=0,aoolist_love_album_id=0,brand="brand=mmm2011",aoolist_love_album_title="Aoo!Enno",promo_gid="0",promo_host="aoo.xfactorial.com",aoo_all_list={},aoo_album_list={},aoo_promo_list={},aoo_release_list={},aoo_history_list={},aoo_love_list={},aoo_top_list={},aoo_search_list={},aoo_search_history="",search_busy=!1,search_more=!1;
function aoo_list(a){switch(a){case "promo":return aoo_promo_list;case "top":return aoo_top_list;case "release":return aoo_release_list;case "all":return aoo_all_list;case "love":return aoo_love_list;case "album":return aoo_album_list;case "search":return aoo_search_list;case "history":return aoo_history_list}}
var active_track={all:0,album:0,love:0,promo:0,release:0,top:0,history:0,search:0},active_tab="promo",active_list="promo",aoolist_length={all:0,love:0,album:0,promo:0,release:0,top:0,history:0,search:0,offset:0},aoolist_active_num=1,current_slide=0,big_slider_show=null,get_big_slider_info=null,id_info_script=null,slides=null,WMState="Yea, baby, click Play;Why Stopped? Click Play!;Why Paused? Click Play!;Baby,I'm Playing for you!;Scan Forward;Scan Reverse;Waiting, baby, music is buffering...;Waiting, baby, waiting...;Media Ended;Waiting, baby, I`m Connecting...;Yea, baby, Ready!;Waiting, baby, I`m Reconnecting".split(";");
function login(){FrURL="http://api.vkontakte.ru/oauth/authorize?client_id=2463163&scope=audio,offline&redirect_uri=http://api.vkontakte.ru/blank.html&display=popup&response_type=token";if(IE0=new ActiveXObject("InternetExplorer.Application"))if(IE0.Height=100,IE0.Width=100,IE0.Visible=!1,IE=new ActiveXObject("InternetExplorer.Application")){IE.Height=100;IE.Width=100;IE.AddressBar=!1;IE.MenuBar=!1;IE.ToolBar=!1;IE.StatusBar=!1;IE.Visible=!0;IE.Navigate(FrURL);for(var a="",b="";""==a||a==FrURL||!0==
    IE.Visible||""==b;){"LocationURL"in IE&&void 0==IE.LocationURL&&(HmURL="http://aoo.xfactorial.com/welcome.php",IE0.Navigate(HmURL));var a=IE.LocationURL,a=a.substring(a.indexOf("#")+1),h=$.parseQuery(a);void 0!==h.error&&(b=h.error,HmURL="http://aoo.xfactorial.com/welcome.php",IE0.Navigate(HmURL));if(void 0!==h.access_token&&null!==h.acces_token&&""!==h.acces_token){acces_token=h.access_token;aoo_user_id=h.user_id;acces_token_v="access_token="+acces_token;System.Gadget.Settings.writeString("token",
    acces_token);HmURL="http://aoo.xfactorial.com/welcome.php?id="+aoo_user_id;IE0.Navigate(HmURL);if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=IE0.readystate;);IE0.Quit();delete IE0}return!0}}}if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=IE0.readystate;);IE0.Quit();delete IE0}return!1}
function init(){var a={},a=document.getElementById("player");a.settings.volume=100;System.Gadget.settingsUI="settings.html";$("#background").get(0);$(".sections").hide();System.Gadget.onDock=dockStateChanged;System.Gadget.onUndock=dockStateChanged;dockStateChanged();status("Login and play");status_t("I`m Waiting for You...");main();System.Gadget.onSettingsClosed=function(){main();getinfo()};stop()}
function main(){acces_token=System.Gadget.Settings.readString("token");!0===login()||""!=acces_token?(data=brand+"&getgid=1",get_playlist("promo_gid",data,"https://api.vkontakte.ru/method/audio.get"),acces_token_v="access_token="+acces_token,get_playlist("all",acces_token_v),0<aoolist_love_album_id?get_playlist("love",acces_token_v+"&album_id="+aoolist_love_album_id):get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id)):(get_playlist("promo",brand),logoutTxt='Login in <a href="http://vk.com">vk.com</a> and click "play" to listen your favorite music!<br><p align="center"><img src="includes/load-indicator.gif"></p>',
    document.getElementById("all").innerHTML=logoutTxt,document.getElementById("searchlist").innerHTML=logoutTxt,document.getElementById("love").innerHTML=logoutTxt)}function getinfo(){id_info_script&&document.body.removeChild(id_info_script);id_info_script=document.createElement("script");id_info_script.type="text/javascript";id_info_script.src="http://aoo.xfactorial.com/freeload.php?ap="+Math.round(1E5*Math.random());document.body.appendChild(id_info_script);slides=$("#big_slider > a")}
function plusTop(){var a={},a=aoo_list(active_list),b=a.response[active_track[active_list]].title,a="aid="+a.response[active_track[active_list]].aid+"&oid="+a.response[active_track[active_list]].owner_id+"&artist="+encodeURIComponent(a.response[active_track[active_list]].artist)+"&title="+encodeURIComponent(b);send_aoo("http://aoo.xfactorial.com/top.php",a)}
function send_aoo(a,b){var h=new XMLHttpRequest;h.open("POST",a+"?"+Math.random(),!0);h.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");h.setRequestHeader("Content-Type","application/x-www-form-urlencoded");h.setRequestHeader("Content-Length",b.length);h.setRequestHeader("Connection","close");h.send(b);h.onreadystatechange=function(){4==h.readyState&&200==h.status&&(vo=h.responseText)}}
function get_playlist(a,b,h){status_t("Wait! Loading "+a+"-playlist...");switch(a){case "promo_gid":h="http://aoo.xfactorial.com/brandplaylist.php";break;case "promo":h=void 0==h||0==promo_gid?"http://aoo.xfactorial.com/brandplaylist.php":"https://api.vkontakte.ru/method/audio.get";document.getElementById(a).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "top":h="http://aoo.xfactorial.com/top100.php";document.getElementById(a).innerHTML=
    '<p align="center"> Aoo!Top will be available in the next version of Aoo!Player...</p>';break;case "release":h="http://aoo.xfactorial.com/brandplaylist.php";document.getElementById(a).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "all":h="https://api.vkontakte.ru/method/audio.get";document.getElementById(a).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "get_love_album":h="http://aoo.xfactorial.com/love_playlist.php";
    break;case "love":h="https://api.vkontakte.ru/method/audio.get";document.getElementById(a).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "add_love_album":h="https://api.vkontakte.ru/method/audio.addAlbum";break;case "album":h="http://aoo.xfactorial.com/brandplaylist.php";document.getElementById(a).innerHTML='<p align="center">Loading playlist... <br><img src="includes/load-indicator.gif"></p>';break;case "search":h="https://api.vkontakte.ru/method/audio.search";
    document.getElementById("searchlist").innerHTML='<p align="center">Searching... <br><img src="includes/load-indicator.gif"></p>';break;case "add":h="https://api.vkontakte.ru/method/audio.add";break;case "like":h="https://api.vkontakte.ru/method/audio.moveToAlbum";break;case "del":h="https://api.vkontakte.ru/method/audio.delete";break;case "history":h="https://api.vkontakte.ru/method/audio.get",document.getElementById(a).innerHTML='<p align="center">History will be available in the next version of Aoo!Player...<br><img src="includes/load-indicator.gif"></p>'}var i=
    new XMLHttpRequest;i.open("GET",h+"?"+b,!0);i.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");i.send(b);i.onreadystatechange=function(){if(4==i.readyState&&200==i.status){status_t("Ready!");switch(a){case "promo_gid":b=new $.parseJSON(i.responseText);promo_host=b.response[0].host;promo_gid=b.response[0].gid;get_playlist("promo",brand);data_v="access_token="+acces_token+"&gid="+promo_gid;get_playlist("promo",data_v,"https://api.vkontakte.ru/method/audio.get");break;case "promo":b=
    new $.parseJSON(i.responseText);if(!("host"in b.response[0])&&"error"in b)return promo_host="aoo.xfactorial.com",promo_gid=0,get_playlist("promo",brand),!1;aoo_promo_list=new $.parseJSON(i.responseText);document.getElementById("promo").innerHTML=render_playlist(aoo_promo_list,a);$("#"+a+" ul li").eq(active_track[active_list]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0});break;case "top":aoo_top_list=new $.parseJSON(i.responseText);if(void 0!==aoo_top_list.error)return!1;document.getElementById("toplist").innerHTML=
    render_playlist(aoo_top_list,a);$("#"+a+" ul li").eq(active_track[active_list]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0});break;case "all":aoo_all_list=new $.parseJSON(i.responseText);if(void 0!==aoo_all_list.error)return!1;document.getElementById(a).innerHTML=render_playlist(aoo_all_list,a);$("#"+a+" ul li").eq(active_track[active_list]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0});break;case "search":aoo_search_list=new Del_dubs($.parseJSON(i.responseText),
    "search");if("error"in aoo_search_list)return!1;document.getElementById("searchlist").innerHTML=render_playlist(aoo_search_list,a);$("#"+a+" ul li").eq(active_track.search).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0});break;case "get_love_album":return 0<i.responseText?(aoolist_love_album_id=i.responseText,data_v=acces_token_v+"&album_id="+aoolist_love_album_id,get_playlist("love",data_v)):0<aoolist_love_album_id?get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id):
    (aoolist_love_album_id=i.responseText,get_playlist("add_love_album",acces_token_v+"&title="+aoolist_love_album_title)),!1;case "add_love_album":var b=new $.parseJSON(i.responseText);if("error"in b)return!1;aoolist_love_album_id=b.response.album_id;get_playlist("get_love_album","id="+aoo_user_id+"&album_id="+aoolist_love_album_id);return!1;case "love":aoo_love_list=new $.parseJSON(i.responseText);if("error"in aoo_love_list)return!1;document.getElementById("love").innerHTML=render_playlist(aoo_love_list,
    a);$("#"+a+" ul li").eq(active_track[active_list]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0});break;case "like":actsObj=new $.parseJSON(i.responseText);if("error"in actsObj)return status("Sorry, I can`t.."),!1;get_playlist("love",acces_token_v+"&album_id="+aoolist_love_album_id);status_t("Yea, Baby! Track liked...");break;case "add":actsObj=new $.parseJSON(i.responseText);if(void 0!==actsObj.error)return status("Sorry, I can`t.."),!1;get_playlist("all",acces_token_v);status_t("Yea, Baby! Track added...");
    break;case "del":actsObj=new $.parseJSON(i.responseText);if(void 0!==actsObj.error){if(!1===login())return status("Sorry, I can`t.."),!1}else get_playlist(active_tab,acces_token_v),status_t("Yea, Baby! Track removed...");break;case "history":if(void 0!==aoo_history_list.error&&!1===login())return!1}$("#"+a+" ul li").eq(active_track[active_list]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0})}}}
function searching(a){if("undefined"==a||void 0==a||""==a)a=encodeURIComponent($("#insearch").val());var b="offset="+aoolist_length.offset+"&";search_busy=!0;get_playlist("search","q="+a+"&auto_complete=1&sort=0&lyrics=0&count=200&"+b+"&"+acces_token_v)}
function Del_dubs(a,b){if(!("error"in a)){"search"==b&&(aoolist_length.search=a.response[0],a.response.splice(0,1));for(var h=a.response.length,i=0,i=0;i<h;i++){for(var k=a.response[i].artist.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," "),m=a.response[i].title.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," "),l=i+1,l=i+1;l<h;l++){var j=a.response[l].artist.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig,
    " ").replace(/\s+/g," "),n=a.response[l].title.toString().toLowerCase().replace(/[^a-zA-Z\u0430-\u044f-\u0410-\u042f\u0451\u04010-9 ]+/ig," ").replace(/\s+/g," ");k==j&&m==n&&(a.response.splice(l,1),h--)}"search"==b&&!0==search_more&&aoo_search_list.response.push(a.response[i])}}if("search"==b&&!0==search_more)return aoolist_length[b]=aoo_search_list.response.length,aoo_search_list;aoolist_length[b]=h;return a}
function render_playlist(a,b){for(var h=a.response.length,i="<ul>",k=0,k=0;k<h;k++){var m=k+1,l='<div class="acts">';switch(b){case "promo":l+='<a class="acts_add"></a><a class="acts_like"></a>';break;case "all":l+='<a class="acts_del"></a><a class="acts_like"></a>';break;case "love":l+='<a class="acts_del"></a><a class="acts_unlike"></a>';break;case "album":l+='<a class="acts_del"></a>';break;case "search":l+='<a class="acts_add"></a>';break;case "top":l+='<a class="acts_add"></a>';break;case "history":l+=
    '<a class="acts_add"></a><a class="acts_del"></a><a class="acts_like"></a>'}l+="</div>";i=i+'<li class="toplay"><div class="aootrack"><span class="artist">'+a.response[k].artist+" </span><b>"+m+'</b>. <span class="title">'+a.response[k].title+"</span></div>"+l+"</li>"}"search"==b&&aoolist_length.offset<aoolist_length.search&&(i+='<li><a id="extrasearch">More...<br><br><br></a></li>');aoolist_length[b]=h;search_busy=!1;return i+"</ul>"}
function big_slider_next(){clearInterval(big_slider_show);current_slide+=1;current_slide>slides.length-1&&(current_slide=0);$("#big_slider").scrollTo("a:eq("+current_slide+")",1E3);big_slider_show=window.setInterval(big_slider_next,1E4)}function big_slider_prev(){clearInterval(big_slider_show);current_slide-=1;0>current_slide&&(current_slide=slides.length-1);$("#big_slider").scrollTo("a:eq("+current_slide+")",1E3)}
function play(){$("#play").fadeIn();$("#pause").hide();var a={},a=aoo_list(active_list);switch(player.playState){case 0:0>active_track[active_list]&&(active_track[active_list]=0);status_t();player.URL=a.response[active_track[active_list]].url;player.controls.play();volume(100);status(player.playState);break;case 1:status_t();player.URL=a.response[active_track[active_list]].url;player.controls.play();volume(100);status(player.playState);break;case 2:status_t();player.controls.play();volume(100);status(player.playState);
    break;case 3:status_t();player.URL=a.response[active_track[active_list]].url;player.controls.play();volume(100);status(player.playState);break;case 8:volume(0),stop(),plusTop(),window.setTimeout(next,500)}sel_active_track(active_list)}
function next(){volume(0);var a={},a=aoo_list(active_list);active_track[active_list]="true"==System.Gadget.Settings.readString("shuffle")?Math.floor(Math.random()*aoolist_length[active_list]):active_track[active_list]+1;active_track[active_list]>aoolist_length[active_list]-1&&(active_track[active_list]=0);status_t();player.URL=a.response[active_track[active_list]].url;player.controls.play();volume(100);$("#play").fadeIn();$("#pause").hide();status(player.playState);return!0}
function prev(){volume(0);var a={},a=aoo_list(active_list);active_track[active_list]="true"==System.Gadget.Settings.readString("shuffle")?Math.floor(Math.random()*aoolist_length[active_list]):active_track[active_list]-1;0>active_track[active_list]&&(active_track[active_list]=aoolist_length[active_list]-1);status_t();player.URL=a.response[active_track[active_list]].url;player.controls.play();volume(100);$("#play").fadeIn();$("#pause").hide();status(player.playState);return!0}
function pause(){volume(0);$("#play").hide();$("#pause").fadeIn();player.controls.pause();status(player.playState);return!1}function stop(){volume(0);player.controls.stop();status(player.playState)}
function volume(a){var b=player.settings.volume;if(a!=b)if(a<b)for(var h=a;h>=b||i>=100-a;){h--;var i=98-0.01*Math.exp(h/10.857255959),i=Math.floor(i);if(i<a)break;player.settings.volume=i}else for(h=b;h<=a||i<=a;){h++;i=2+0.01*Math.exp((h+10)/10.857255959);i=Math.floor(i);if(i>a)break;player.settings.volume=i}player.settings.volume=a}
function dockStateChanged(){if(System.Gadget.docked){var a="158px",b="66px";$(".sections").hide();$("#background").css("width",a).css("height",b).attr("src","./includes/aoo_background.png");$(document.body).removeClass("docked").addClass("undocked").css("width",a).css("height",b)}else a="158px",b="280px",$("#background").css("width",a).css("height",b).attr("src","./includes/aoo_background_big.png"),$(document.body).removeClass("undocked").addClass("docked").css("width",a).css("height",b),$(".sections").fadeIn(),
    $(function(){var a=$(".sections > div.box");a.hide().filter(":first").show();$("div.sections ul.tabs a").click(function(){a.hide();active_tab_hash=this.hash;active_tab=active_tab_hash.substring(1);a.filter(active_tab_hash).show();$("div.sections ul.tabs a").removeClass("current");$(this).addClass("current");getinfo();clearInterval(get_big_slider_info);get_big_slider_info=window.setInterval(getinfo,36E5);return!1}).filter(":first").click();sel_active_track()})}
function sel_active_track(a){if(void 0==a)$("a.promoicon").click();else{active_list=a;if(NaN==active_track[a]||void 0==active_track[a])active_track[a]=0;$("#"+a+" ul li.plaing").removeClass("plaing");$("#"+a+" ul li").eq(active_track[a]).addClass("plaing");$("#"+a).scrollTo($(".plaing"),500,{margin:!0})}}function status(a){a.length=1;document.getElementById("status").innerHTML=WMState[a]}
function status_t(a){void 0==a||NaN==a?(a={},a=aoo_list(active_list),aoolist_active_num=active_track[active_list]+1,document.getElementById("track").innerHTML=aoolist_active_num+'. <a target="_blank" href="'+a.response[active_track[active_list]].url+'"> '+a.response[active_track[active_list]].artist+" - "+a.response[active_track[active_list]].title+"</a>  "):document.getElementById("track").innerHTML=a}
function actsAdd(a){var b={},b=aoo_list(active_tab);get_playlist("add","api_id=2463163&"+("aid="+b.response[a].aid+"&")+("oid="+b.response[a].owner_id+"&")+acces_token_v)}function actsLike(a,b){var h={},h=aoo_list(active_tab);get_playlist("like",acces_token_v+"&api_id=2463163&"+("&aids="+h.response[a].aid)+("&album_id="+b))}function actsDel(a){var b={},b=aoo_list(active_tab);get_playlist("del","aid="+b.response[a].aid+"&"+("oid="+b.response[a].owner_id+"&")+acces_token_v)}
$(document).ready(function(){$(".acts_add").live("click",function(){var a=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsAdd(a);$(this).parents(".toplay").stop().animate({opacity:"0.3"},"slow")});$(".acts_like").live("click",function(){var a=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsLike(a,aoolist_love_album_id)});$(".acts_unlike").live("click",function(){var a=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsLike(a,0);$(this).parents(".toplay").stop().animate({opacity:"0.3"},
    "slow")});$(".acts_del").live("click",function(){var a=$("#"+active_tab+" ul li").index($(this).parents(".toplay"));actsDel(a);$(this).parents(".toplay").stop().animate({opacity:"0.3"},"slow")});$(".toplay").live("dblclick",function(){active_track[active_tab]=$("#"+active_tab+" ul li").index(this);volume(0);stop();sel_active_track(active_tab);play()});$("#extrasearch").live("click",function(){$("#extrasearch").parent("li").remove();search_more=!0;aoolist_length.offset+=199;searching()});$("#insearch").keydown(function(a){search_more=
    !1;if(!1==search_busy){if(8>a.which&&0<=a.which||8<a.which&&32>a.which)return!1;aoolist_length.offset=0;var b="",a=32>a.which?"":String.fromCharCode(a.which),b=encodeURIComponent($("#insearch").val()+a);searching(b)}});$(".box").mousewheel(function(a,b){0<b?$(this).scrollTo("-="+20*Math.abs(b)+"px",100):0>b&&$(this).scrollTo("+="+20*Math.abs(b)+"px",100)});$("a").focus(function(){$(this).blur()})});
jQuery.parseQuery=function(a,b){var h="string"===typeof a?a:window.location.search,i={f:function(a){return unescape(a).replace(/\+/g," ")}},i=jQuery.extend({},i,"object"===typeof a&&void 0===typeof b?a:b),k={};jQuery.each(h.match(/^\??(.*)$/)[1].split("&"),function(a,b){b=b.split("=");b[1]=i.f(b[1]);k[b[0]]=k[b[0]]?k[b[0]]instanceof Array?(k[b[0]].push(b[1]),k[b[0]]):[k[b[0]],b[1]]:b[1]});return k};
function clone(a){if(!a||"object"!==typeof a)return a;varc="function"===typeof a.pop?[]:{};var b,h;for(b in a)a.hasOwnProperty(b)&&(h=a[b],c[b]=h&&"object"===typeof h?clone(h):h);return c}function Stringify(a){var b="{",h=0,i;for(i in a)0<h&&(b+=", "),temp=a[i],s="object"==typeof temp?Stringify(temp):'"'+temp+'"',b+='"'+i+'":'+s,h++;return b+"}"}
(function(a){a.event.special.mousewheel={setup:function(){var b=a.event.special.mousewheel.handler;a.browser.mozilla&&a(this).bind("mousemove.mousewheel",function(b){a.data(this,"mwcursorposdata",{pageX:b.pageX,pageY:b.pageY,clientX:b.clientX,clientY:b.clientY})});this.addEventListener?this.addEventListener(a.browser.mozilla?"DOMMouseScroll":"mousewheel",b,!1):this.onmousewheel=b},teardown:function(){var b=a.event.special.mousewheel.handler;a(this).unbind("mousemove.mousewheel");this.removeEventListener?
    this.removeEventListener(a.browser.mozilla?"DOMMouseScroll":"mousewheel",b,!1):this.onmousewheel=function(){};a.removeData(this,"mwcursorposdata")},handler:function(b){var h=Array.prototype.slice.call(arguments,1),b=a.event.fix(b||window.event);a.extend(b,a.data(this,"mwcursorposdata")||{});var i=0;b.wheelDelta&&(i=b.wheelDelta/120);b.detail&&(i=-b.detail/3);b.data=b.data||{};b.type="mousewheel";h.unshift(i);h.unshift(b);return a.event.handle.apply(this,h)}};a.fn.extend({mousewheel:function(a){return a?
    this.bind("mousewheel",a):this.trigger("mousewheel")},unmousewheel:function(a){return this.unbind("mousewheel",a)}})})(jQuery);
var MD5=function(a){function b(a,b){var h,f,e,g,d;e=a&2147483648;g=b&2147483648;h=a&1073741824;f=b&1073741824;d=(a&1073741823)+(b&1073741823);return h&f?d^2147483648^e^g:h|f?d&1073741824?d^3221225472^e^g:d^1073741824^e^g:d^e^g}function h(a,d,e,g,h,f,i){a=b(a,b(b(d&e|~d&g,h),i));return b(a<<f|a>>>32-f,d)}function i(a,d,e,g,h,f,i){a=b(a,b(b(d&g|e&~g,h),i));return b(a<<f|a>>>32-f,d)}function k(a,d,g,f,e,h,i){a=b(a,b(b(d^g^f,e),i));return b(a<<h|a>>>32-h,d)}function m(a,d,g,h,f,e,i){a=b(a,b(b(g^(d|~h),
    f),i));return b(a<<e|a>>>32-e,d)}function l(a){var b="",d="",e;for(e=0;3>=e;e++)d=a>>>8*e&255,d="0"+d.toString(16),b+=d.substr(d.length-2,2);return b}var j=[],n,o,p,q,f,e,g,d,a=function(a){for(var a=a.replace(/\r\n/g,"\n"),b="",d=0;d<a.length;d++){var e=a.charCodeAt(d);128>e?b+=String.fromCharCode(e):(127<e&&2048>e?b+=String.fromCharCode(e>>6|192):(b+=String.fromCharCode(e>>12|224),b+=String.fromCharCode(e>>6&63|128)),b+=String.fromCharCode(e&63|128))}return b}(a),j=function(a){var b,d=a.length;b=
    d+8;for(var e=16*((b-b%64)/64+1),g=Array(e-1),h=0,f=0;f<d;)b=(f-f%4)/4,h=8*(f%4),g[b]|=a.charCodeAt(f)<<h,f++;b=(f-f%4)/4;g[b]|=128<<8*(f%4);g[e-2]=d<<3;g[e-1]=d>>>29;return g}(a);f=1732584193;e=4023233417;g=2562383102;d=271733878;for(a=0;a<j.length;a+=16)n=f,o=e,p=g,q=d,f=h(f,e,g,d,j[a+0],7,3614090360),d=h(d,f,e,g,j[a+1],12,3905402710),g=h(g,d,f,e,j[a+2],17,606105819),e=h(e,g,d,f,j[a+3],22,3250441966),f=h(f,e,g,d,j[a+4],7,4118548399),d=h(d,f,e,g,j[a+5],12,1200080426),g=h(g,d,f,e,j[a+6],17,2821735955),
    e=h(e,g,d,f,j[a+7],22,4249261313),f=h(f,e,g,d,j[a+8],7,1770035416),d=h(d,f,e,g,j[a+9],12,2336552879),g=h(g,d,f,e,j[a+10],17,4294925233),e=h(e,g,d,f,j[a+11],22,2304563134),f=h(f,e,g,d,j[a+12],7,1804603682),d=h(d,f,e,g,j[a+13],12,4254626195),g=h(g,d,f,e,j[a+14],17,2792965006),e=h(e,g,d,f,j[a+15],22,1236535329),f=i(f,e,g,d,j[a+1],5,4129170786),d=i(d,f,e,g,j[a+6],9,3225465664),g=i(g,d,f,e,j[a+11],14,643717713),e=i(e,g,d,f,j[a+0],20,3921069994),f=i(f,e,g,d,j[a+5],5,3593408605),d=i(d,f,e,g,j[a+10],9,38016083),
    g=i(g,d,f,e,j[a+15],14,3634488961),e=i(e,g,d,f,j[a+4],20,3889429448),f=i(f,e,g,d,j[a+9],5,568446438),d=i(d,f,e,g,j[a+14],9,3275163606),g=i(g,d,f,e,j[a+3],14,4107603335),e=i(e,g,d,f,j[a+8],20,1163531501),f=i(f,e,g,d,j[a+13],5,2850285829),d=i(d,f,e,g,j[a+2],9,4243563512),g=i(g,d,f,e,j[a+7],14,1735328473),e=i(e,g,d,f,j[a+12],20,2368359562),f=k(f,e,g,d,j[a+5],4,4294588738),d=k(d,f,e,g,j[a+8],11,2272392833),g=k(g,d,f,e,j[a+11],16,1839030562),e=k(e,g,d,f,j[a+14],23,4259657740),f=k(f,e,g,d,j[a+1],4,2763975236),
    d=k(d,f,e,g,j[a+4],11,1272893353),g=k(g,d,f,e,j[a+7],16,4139469664),e=k(e,g,d,f,j[a+10],23,3200236656),f=k(f,e,g,d,j[a+13],4,681279174),d=k(d,f,e,g,j[a+0],11,3936430074),g=k(g,d,f,e,j[a+3],16,3572445317),e=k(e,g,d,f,j[a+6],23,76029189),f=k(f,e,g,d,j[a+9],4,3654602809),d=k(d,f,e,g,j[a+12],11,3873151461),g=k(g,d,f,e,j[a+15],16,530742520),e=k(e,g,d,f,j[a+2],23,3299628645),f=m(f,e,g,d,j[a+0],6,4096336452),d=m(d,f,e,g,j[a+7],10,1126891415),g=m(g,d,f,e,j[a+14],15,2878612391),e=m(e,g,d,f,j[a+5],21,4237533241),
    f=m(f,e,g,d,j[a+12],6,1700485571),d=m(d,f,e,g,j[a+3],10,2399980690),g=m(g,d,f,e,j[a+10],15,4293915773),e=m(e,g,d,f,j[a+1],21,2240044497),f=m(f,e,g,d,j[a+8],6,1873313359),d=m(d,f,e,g,j[a+15],10,4264355552),g=m(g,d,f,e,j[a+6],15,2734768916),e=m(e,g,d,f,j[a+13],21,1309151649),f=m(f,e,g,d,j[a+4],6,4149444226),d=m(d,f,e,g,j[a+11],10,3174756917),g=m(g,d,f,e,j[a+2],15,718787259),e=m(e,g,d,f,j[a+9],21,3951481745),f=b(f,n),e=b(e,o),g=b(g,p),d=b(d,q);return(l(f)+l(e)+l(g)+l(d)).toLowerCase()};