var GetAT,q,acces_token,aoo_user_id,acces_token_v;function settingsClosing(a){a.closeAction==a.Action.commit&&($(".error").removeClass("error"),System.Gadget.Settings.writeString("token",acces_token),a.cancel||($("#shuffle").is(":checked")?System.Gadget.Settings.writeString("shuffle","true"):System.Gadget.Settings.writeString("shuffle","false")))}
function main(){"true"==System.Gadget.Settings.readString("shuffle")?$("#shuffle").attr("checked","checked"):$("#shuffle").removeAttr("checked");acces_token=System.Gadget.Settings.readString("token");acces_token_v="access_token="+acces_token;""!==acces_token&&login();get_i("users.get",acces_token_v+"&fields=first_name,last_name,nickname,photo_medium_rec&uids="+aoo_user_id);checkUpdates();System.Gadget.onSettingsClosing=settingsClosing}
function logout(){FrURL="http://api.vkontakte.ru/oauth/logout?client_id=2463163&redirect_uri=http://vkontakte.ru&user_id="+aoo_user_id;var a;if(a=new ActiveXObject("InternetExplorer.Application")){a.Height=190;a.Width=620;a.AddressBar=!0;a.MenuBar=!1;a.ToolBar=!1;a.StatusBar=!1;a.Visible=!1;a.Navigate(FrURL);if("Quit"in a){for(;4!==a.readystate&&4!=a.readystate;);a.Quit();delete a}$("#tokenin").fadeIn();System.Gadget.Settings.writeString("token","");$("#login").fadeIn();return!0}}
function login(){FrURL="http://api.vkontakte.ru/oauth/authorize?client_id=2463163&scope=audio,offline&redirect_uri=http://api.vkontakte.ru/blank.html&display=popup&response_type=token";if(IE0=new ActiveXObject("InternetExplorer.Application"))if(IE0.Height=190,IE0.Width=620,IE0.Visible=!1,IE=new ActiveXObject("InternetExplorer.Application")){IE.Height=500;IE.Width=450;IE.AddressBar=!1;IE.MenuBar=!1;IE.ToolBar=!1;IE.StatusBar=!1;IE.Visible=!0;IE.Navigate(FrURL);for(var a="",c="";""==a||a==FrURL||!0==
    IE.Visible||""==c;){"LocationURL"in IE&&void 0==IE.LocationURL&&(HmURL="http://aoo.xfactorial.com/welcome.php",IE0.Navigate(HmURL));var a=IE.LocationURL,a=a.substring(a.indexOf("#")+1),b=$.parseQuery(a);void 0!==b.error&&(c=b.error,HmURL="http://aoo.xfactorial.com/welcome.php",IE0.Navigate(HmURL));if(void 0!==b.access_token&&null!==b.acces_token&&""!==b.acces_token){acces_token=b.access_token;aoo_user_id=b.user_id;acces_token_v="access_token="+acces_token;System.Gadget.Settings.writeString("token",
    acces_token);HmURL="http://aoo.xfactorial.com/welcome.php?id="+aoo_user_id;IE0.Navigate(HmURL);get_i("users.get",acces_token_v+"&fields=first_name,last_name,nickname,photo_medium_rec&uids="+aoo_user_id);if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=IE0.readystate;);IE0.Quit();delete IE0}return!0}}}if("Quit"in IE){for(;4!==IE.readystate&&4!=IE.readystate;);IE.Quit();delete IE}if("Quit"in IE0){for(;4!==IE0.readystate&&4!=
    IE0.readystate;);IE0.Quit();delete IE0}return!1}function user(){if(IE6=new ActiveXObject("InternetExplorer.Application"))IE6.Height=500,IE6.Width=450,IE6.AddressBar=!0,IE6.MenuBar=!1,IE6.ToolBar=!1,IE6.StatusBar=!1,IE6.Navigate("http://vkontakte.ru/"),IE6.Visible=!0;return!1}
function get_i(a,c){switch(a){case "users.get":url="https://api.vkontakte.ru/method/users.get"}var b=new XMLHttpRequest;b.open("GET",url+"?"+c,!0);b.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");b.send(c);b.onreadystatechange=function(){if(4==b.readyState&&200==b.status)switch(a){case "users.get":qi=new $.parseJSON(b.responseText),void 0!==qi.error?$("#login").fadeIn():($("#login").fadeOut(),$("#tokenin").fadeIn(),document.getElementById("userphoto").innerHTML='<img id="user" src="'+
    qi.response[0].photo_medium_rec+'"><br>',document.getElementById("name").innerHTML=qi.response[0].first_name+" "+qi.response[0].last_name+"<br>")}}}
$.parseQuery=function(a,c){var b="string"===typeof a?a:window.location.search,e={f:function(a){return unescape(a).replace(/\+/g," ")}},e=$.extend({},e,"object"===typeof a&&void 0===typeof c?a:c),d={};$.each(b.match(/^\??(.*)$/)[1].split("&"),function(a,b){b=b.split("=");b[1]=e.f(b[1]);d[b[0]]=d[b[0]]?d[b[0]]instanceof Array?(d[b[0]].push(b[1]),d[b[0]]):[d[b[0]],b[1]]:b[1]});return d};
$(document).ready(function(){main();document.getElementById("userphoto").onclick=function(){var a=window.open("http://vkontakte.ru/","blank","width=1000,height=600");a.onload;return!1};document.getElementById("logout").onclick=function(){logout()&&($("#tokenin").fadeOut(),$("#login").fadeIn())};document.getElementById("login").onclick=function(){login()&&$("#login").fadeOut()}});
function getURL(a){var c=new XMLHttpRequest;c.open("GET",a,!0);c.setRequestHeader("If-Modified-Since","Sat, 1 Jan 2000 00:00:00 GMT");c.onreadystatechange=function(){if(4==c.readyState&&200==c.status){var a=null,a=c.responseText;if(!1===a)return!1;if(2.2<parseFloat(a))document.getElementById("about").innerHTML='<p><a localize="aboutNext,href:aboutHref,title:aboutTitle" href="http://aoo.xfactorial.com/">Download new Aoo!Player</a></p>';else return document.getElementById("about").innerHTML='<p><a localize="about,href:aboutHref,title:aboutTitle" href="http://aoo.xfactorial.com/">Aoo!Player</a></p>',
    !1}return!0};c.send(null)}function checkUpdates(){getURL("http://aoo.xfactorial.com/version.php")};